package com.experian.ind.prime.ingest.core.shared_models.parser_models.commercial

/**
 * DataFrame-2 Parsed Records model
 * Contains identifiers and up to 49 field-tag columns (schema-driven mapping).
 * Note: Column names beginning with digits are defined using backticks to be valid Scala identifiers.
 */
case class DF2ParsedRecords(
  FileLoadID: Long,
  BatchID: Int,
  RecordID: String,
  Type_of_Line: String,
  Segment_Tag: String,
  Segment_Repeat_Id: String,
  `01_field_tag`: String,
  `02_field_tag`: String,
  `03_field_tag`: String,
  `04_field_tag`: String,
  `05_field_tag`: String,
  `06_field_tag`: String,
  `07_field_tag`: String,
  `08_field_tag`: String,
  `09_field_tag`: String,
  `10_field_tag`: String,
  `11_field_tag`: String,
  `12_field_tag`: String,
  `13_field_tag`: String,
  `14_field_tag`: String,
  `15_field_tag`: String,
  `16_field_tag`: String,
  `17_field_tag`: String,
  `18_field_tag`: String,
  `19_field_tag`: String,
  `20_field_tag`: String,
  `21_field_tag`: String,
  `22_field_tag`: String,
  `23_field_tag`: String,
  `24_field_tag`: String,
  `25_field_tag`: String,
  `26_field_tag`: String,
  `27_field_tag`: String,
  `28_field_tag`: String,
  `29_field_tag`: String,
  `30_field_tag`: String,
  `31_field_tag`: String,
  `32_field_tag`: String,
  `33_field_tag`: String,
  `34_field_tag`: String,
  `35_field_tag`: String,
  `36_field_tag`: String,
  `37_field_tag`: String,
  `38_field_tag`: String,
  `39_field_tag`: String,
  `40_field_tag`: String,
  `41_field_tag`: String,
  `42_field_tag`: String,
  `43_field_tag`: String,
  `44_field_tag`: String,
  `45_field_tag`: String,
  `46_field_tag`: String,
  `47_field_tag`: String,
  `48_field_tag`: String,
  `49_field_tag`: String,
  Field_Tag: String,
  Field_Value: String,
  Error_Code: String,
  Error_Message: String,
  Rule_Id: String,
  Metric_Code: String,
  Reject_Type: String,
  CreatedAt: String
)